package com.qiguliuxing.dts.db.dao;

import java.util.List;
import java.util.Map;

import com.qiguliuxing.dts.vo.AddressVO;
import org.apache.ibatis.annotations.Param;

public interface DtsAddressMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_address
     *
     * @mbg.generated
     */
    List<AddressVO> queryAddressList(Map<String, Object> params);

    AddressVO findById(Long id);

    int update(AddressVO address);

    int add(AddressVO address);

    int resetDefault(@Param("userId") String userId);

    int resetPickup(@Param("userId") String userId);

    /**
     * 根据用户ID和地址ID删除地址
     * @param userId 用户ID
     * @param addressId 地址ID
     * @return 删除的行数
     */
    int deleteByUserIdAndId(@Param("userId") String userId,
                            @Param("addressId") Long addressId);
}
