package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.DtsUser;
import com.qiguliuxing.dts.db.domain.DtsUserExample;
import java.util.List;
import java.util.Map;

import com.qiguliuxing.dts.vo.InvitationRecordVO;
import com.qiguliuxing.dts.vo.UserVO;
import org.apache.ibatis.annotations.Param;

public interface DtsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    long countByExample(DtsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int deleteByExample(DtsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int insert(DtsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int insertSelective(DtsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUser selectOneByExample(DtsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUser selectOneByExampleSelective(@Param("example") DtsUserExample example, @Param("selective") DtsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<DtsUser> selectByExampleSelective(@Param("example") DtsUserExample example, @Param("selective") DtsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    List<DtsUser> selectByExample(DtsUserExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") DtsUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    DtsUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    DtsUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DtsUser record, @Param("example") DtsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DtsUser record, @Param("example") DtsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DtsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DtsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") DtsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);


    /**
     *  动态查询用户列表（后台管理系统）
     * @param params
     * @return
     */
    List<UserVO> queryUserList(Map<String, Object> params);

    /**
     * 查询邀请记录（小程序客户端）
     * @param inviterId 邀请人ID
     * @return 邀请记录列表
     */
    List<InvitationRecordVO> selectInvitationRecords(@Param("inviterId") String inviterId);

    /**
     * 插入用户（小程序客户端）
     * @param user 用户实体
     * @return 影响行数
     */
    int insertUser(UserVO user);

    /**
     * 检查用户ID是否存在
     * @param wxOpenId 微信ID
     * @return 是否存在
     */
    boolean existsByWxOpenId(@Param("wxOpenId") String wxOpenId);


    /**
     * 生成用户ID
     * @return 用户ID
     */
    String getNextUserId();

    /**
     * 统计用户数量
     * @return
     */
    int countUser();

    int updateSpiritPower(
            @Param("userId") String userId,
            @Param("value") int value,
            @Param("isAdd") boolean isAdd
    );

    Integer selectSpiritPower(@Param("userId") String userId);
}
